// YouTube Cookie Authentication
// Login window, cookie extraction, Netscape cookie file for yt-dlp.

const { BrowserWindow, session } = require("electron");
const path = require("path");
const fs = require("fs");
const os = require("os");
const { log, logError } = require("./utils");

const PARTITION = "persist:youtube-login";
const LOGIN_URL =
    "https://accounts.google.com/ServiceLogin?service=youtube&continue=https://www.youtube.com/";

let cookiePath = null;

function getCookiePath() {
    if (!cookiePath) {
        cookiePath = path.join(os.tmpdir(), "arcdlp-cookies.txt");
    }
    return cookiePath;
}

async function hasCookies() {
    const ses = session.fromPartition(PARTITION);
    const cookies = await ses.cookies.get({ domain: ".youtube.com" });
    return cookies.length > 0;
}

async function getCookieFile() {
    const has = await hasCookies();
    if (!has) return null;

    await writeCookieFile();
    const p = getCookiePath();
    return fs.existsSync(p) ? p : null;
}

function openLoginWindow(parentWindow) {
    return new Promise((resolve) => {
        const win = new BrowserWindow({
            width: 500,
            height: 700,
            parent: parentWindow || undefined,
            modal: !!parentWindow,
            title: "Sign in to YouTube",
            webPreferences: {
                partition: PARTITION,
                nodeIntegration: false,
                contextIsolation: true,
            },
            autoHideMenuBar: true,
        });

        let resolved = false;

        function done(result) {
            if (resolved) return;
            resolved = true;
            if (!win.isDestroyed()) win.close();
            resolve(result);
        }

        win.webContents.on("did-navigate", (_e, url) => {
            log("Login nav:", url);
            if (isYouTubeHome(url)) {
                log("Login detected, landed on YouTube");
                // Small delay to let cookies settle
                setTimeout(() => done(true), 1000);
            }
        });

        win.webContents.on("did-navigate-in-page", (_e, url) => {
            if (isYouTubeHome(url)) {
                setTimeout(() => done(true), 1000);
            }
        });

        win.on("closed", () => done(false));

        win.loadURL(LOGIN_URL);
    });
}

async function clearCookies() {
    const ses = session.fromPartition(PARTITION);
    await ses.clearStorageData();
    // Remove cookie file
    const p = getCookiePath();
    try {
        fs.unlinkSync(p);
    } catch {
        //
    }
    log("YouTube cookies cleared");
}

function isYouTubeHome(url) {
    try {
        const u = new URL(url);
        return u.hostname === "www.youtube.com" &&
            (u.pathname === "/" || u.pathname.startsWith("/feed"));
    } catch {
        return false;
    }
}

async function writeCookieFile() {
    const ses = session.fromPartition(PARTITION);
    const cookies = await ses.cookies.get({});

    // Filter to relevant domains (Google + YouTube)
    const relevant = cookies.filter((c) => {
        const d = c.domain || "";
        return d.includes("youtube.com") || d.includes("google.com") ||
            d.includes("googleapis.com");
    });

    if (relevant.length === 0) {
        log("No YouTube/Google cookies found");
        return;
    }

    const lines = ["# Netscape HTTP Cookie File", "# Generated by ArcDLP", ""];

    for (const c of relevant) {
        const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
        const flag = domain.startsWith(".") ? "TRUE" : "FALSE";
        const pathVal = c.path || "/";
        const secure = c.secure ? "TRUE" : "FALSE";
        const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
        lines.push(
            `${domain}\t${flag}\t${pathVal}\t${secure}\t${expiry}\t${c.name}\t${c.value}`,
        );
    }

    const filePath = getCookiePath();
    fs.writeFileSync(filePath, lines.join("\n"), "utf8");
    log("Wrote", relevant.length, "cookies to", filePath);
}

module.exports = { hasCookies, getCookieFile, openLoginWindow, clearCookies };
